# Generated by Django 3.2.15 on 2022-09-07 09:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('mainImage', models.CharField(max_length=300)),
                ('brandCategory', models.CharField(max_length=200)),
                ('intro', models.CharField(max_length=1000)),
                ('overView', models.CharField(max_length=1000)),
                ('attrs', models.ManyToManyField(to='Products.Attr')),
                ('cart', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('category_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold', models.BigIntegerField(blank=True, default=0, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2022, 9, 7, 9, 24, 55, 156844))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.category')),
                ('prod_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
                ('user_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BigIntegerField(blank=True, default=0, null=True)),
                ('last', models.CharField(default='True', max_length=10)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2022, 9, 7, 9, 24, 55, 155868))),
                ('prod_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
                ('user_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
