# Generated by Django 3.2.15 on 2022-09-05 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 17, 54, 25, 678358)),
        ),
        migrations.AlterField(
            model_name='sold',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 17, 54, 25, 678358)),
        ),
    ]
