# Generated by Django 3.2.15 on 2022-09-07 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 18, 42, 11, 280510)),
        ),
        migrations.AlterField(
            model_name='sold',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 18, 42, 11, 281486)),
        ),
    ]
