# Generated by Django 3.2.15 on 2022-09-13 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20220913_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 18, 59, 33, 130139)),
        ),
        migrations.AlterField(
            model_name='sold',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 18, 59, 33, 131121)),
        ),
    ]
