# Generated by Django 3.2.15 on 2022-09-01 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_seen_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 14, 3, 58, 84670)),
        ),
    ]
