# Generated by Django 3.2.15 on 2022-09-10 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20220907_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='discount',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='seen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 14, 56, 15, 429007)),
        ),
        migrations.AlterField(
            model_name='sold',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 14, 56, 15, 434867)),
        ),
    ]
