# Generated by Django 3.2.15 on 2022-09-10 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20220910_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 15, 3, 22, 127959)),
        ),
        migrations.AlterField(
            model_name='sold',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 15, 3, 22, 129913)),
        ),
        migrations.AlterField(
            model_name='sold',
            name='discount',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
